### ISSUE TITLE
Including apk compare in a gitlab CI/CD pipeline script breaks the script. Error inside the description.

### ISSUE THREAD

**Issue by AresDragoi** [warnyul/docker-android-build-tools#21]
_**$ find ./ -name "*.apk" | xargs -I {} ./analyze.sh {} abc
Exception in thread "main" java.lang.IllegalStateException: The tools directory property is not set, please make sure you are executing apkanalyzer. Got /opt/android-sdk-linux/cmdline-tools**_

My specific usecase:

`relevant part of .yaml file configuration:`
```dockerfile
analyze_samples:
    stage: analyze
    image: warnyul/android-build-tools 
    script:
        - ls -lah
        - find ./ -name "*.sh" | xargs -I {} chmod a+x {}
        - find ./ -name "*.apk" | xargs -I {} ./analyze.sh {} abc
        - pwd && ls -lah && ls obf/
``` 

`analyze.sh script:`

```shell
#!/bin/bash

#outputs number of defined methods, referenced methods, byte size respectively  
apkanalyzer dex packages "$1" | head -n 1 | awk '$1 {print $3, $4, $5}' # works just fine

apkanalyzer compare "$1" "obf/$1.obf" #causes the error. Verified that parameters are correct. Tried it with literals too.
```

**Comment by warnyul** [comment]
I think this issue is related with this SO question: https://stackoverflow.com/questions/60925741/cant-execute-apkanalyzer

**Comment by warnyul** [comment]
The fixed version available on docker hub.
